//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SearchGenerator
{
    using System;
    using System.Text;
    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("SharpRazor", "1.0.0.0")]
    internal class Matcher
    {
        #region constructor
        Flag[] flags;
        int i;

        public Matcher(Flag[] flags, int i)
        {
            this.flags = flags;
            this.i = i;
        }
        #endregion

        #region basic members
        private readonly StringBuilder sb = new StringBuilder();
        private string executed;

        private void WriteLiteral(string text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                sb.Append(text);
            }
        }

        private void Write(object value)
        {
            if (value != null)
            {
                sb.Append(value);
            }
        }

        public override string ToString()
        {
            return executed;
        }
        #endregion

        public string Execute()
        {
            WriteLiteral(@"namespace SearchTest.Search.GeneratedSolution");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"{");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"    using Search.NaiveSolution;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"    public class GenMatcher");
            Write(i);
            WriteLiteral(@" : SearchCriteria, IMatcher");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"    {");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        public GenMatcher");
            Write(i);
            WriteLiteral(@"(SearchCriteria criteria)");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        {");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            NonClosedOnly = criteria.NonClosedOnly;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            NoAnswerOnly = criteria.NoAnswerOnly;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"            BountiesOnly = criteria.BountiesOnly;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        }");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        public bool Match(Post post)");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        {");
            WriteLiteral(Environment.NewLine);
            foreach (var flag in flags)
            {
                WriteLiteral(@"            if(post.");
                Write(flag.Condition);
                WriteLiteral(@") return false;");
                WriteLiteral(Environment.NewLine);
            }
            WriteLiteral(@"            return true;");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"        }");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"    }");
            WriteLiteral(Environment.NewLine);
            WriteLiteral(@"}");
            WriteLiteral(Environment.NewLine);

            return executed = sb.ToString();
        }
    }
}
